FROM alpine
COPY ./ss-libev /tmp/ev
RUN  mv /tmp/ev/lib* /lib/ \
	&& mv /tmp/ev/ss-manager /bin/ \ 
	&& mv /tmp/ev/v2ray-plugin /bin/ \ 
	&& rm -rf /tmp/ev
ENTRYPOINT ["/bin/ss-manager"]
CMD ["--manager-address","0.0.0.0:7788"]